### ISSUE TITLE
Event error since update to 3.0.1

### ISSUE THREAD

**Issue by RedLucas** [vuejs/vue-devtools#220]
I'm not sure what the best way to revert to v2 is but I'm getting Uncaught `TypeError: e.startsWith is not a function`. When I try to execute a method in vuejs. Didn't used to happen. You should know I'm still using Vuejs 1, we're not quite there yet to update so let's just move on from that. 

This is the event handler causing the issue. I know it looks silly but I need to do this for my purposes. 
`var vue = this;
  var iframe = $('#iframe').contents();
iframe.find('a').click(function (e) {
          vue.replaceInit(e);
          e.preventDefault();
        });
`

It 100% worked before the v3 update.

**Comment by pavoooo** [comment]
we also meet the same problems

**Comment by iampomelo** [comment]
![image](https://cloud.githubusercontent.com/assets/12301275/21710150/c6cf20e8-d421-11e6-9815-944e095c629b.png)

**Comment by EroTiXx** [comment]
Same problem

**Comment by noetix** [comment]
Yep. =/

**Comment by DannyFeliz** [comment]
Same problem here 👎

**Comment by DanSmith83** [comment]
Getting this calling this.$broadcast with VueJS 1.0.28

**Comment by RedLucas** [comment]
Yes, I am also using $broadcast in the `vue.replaceInit(e);` function referenced above.
